name: Backend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install php Packges  
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            
            FLAG_FILE="/home/${{ secrets.SERVER_USER }}/.Setup_Packages_First_Time"
            TARGET_DIR="/var/www/laravel"
            if [ ! -f "$FLAG_FILE" ]; then
            echo "ٍSetup php Packages..."
            sudo apt update 
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt install -y php8.2 php8.2-cli php8.2-mbstring php8.2-xml php8.2-mysql php8.2-curl php8.2-zip php8.2-intl composer unzip
            touch "$FLAG_FILE"
            fi
            # 2. Clone or Pull
            if [ ! -d "$TARGET_DIR" ]; then
              echo "Cloning repo for the first time..."
              sudo git clone -b main --single-branch https://github.com/mohamed-abouseada121/laravel.git $TARGET_DIR
              sudo chown -R ubuntu:ubuntu /var/www/laravel
              echo "DB_CONNECTION=mysql" > .env
              echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
              echo "DB_PORT=3306" >> .env
              echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
              echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            else
              echo "Pulling latest changes..."
              cd $TARGET_DIR
              git stash
              git pull origin main
            fi
            
            cd $TARGET_DIR

            composer install
            php artisan migrate --force
